name: UPM
on:
  release:
    types:
    - published
jobs:
  release:
    name: Update Master Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Merge develop
      run: |
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout master
        git pull origin master
        git merge origin/develop        
        git push -f -u origin master