name: Push to develop
on:
  push:
    branches:
    - development
jobs:
  release:
    name: Update develop package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create develop package branch
      run: |
        git checkout -b develop
        mv "$PKG_ROOT" /tmp/test
        rm -rf *
        mv /tmp/test .
        cd test
        mv * ../
        cd ..
        git add .
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git commit -am "Packaged project"
        git push -f -u origin develop
      env:
        PKG_ROOT: "Packages/se.hertzole.cecil-attributes"