name: Test Unity 2020
on:
  push:
    branch:
    - development

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Run Unity 2020.3 tests
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    # Cache
    - uses: actions/cache@v2.1.4
      with:
        path: Library
        key: Library

    - name: Run tests
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: "2020.3.6f1"