name: Test Unity 2020
on:
  push:
    branch:
    - development
    paths:
    - 'Assets/**'
    - 'Packages/**'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Run Unity 2020.3 tests
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Run tests
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: "2020.3.25f1"