name: Test Unity 2021
on:
  push:
    branch:
    - development

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Run Unity 2021.3 tests
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Run tests
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: "2021.3.7f1"